package com.example.dara.arbridge

object DaraArContract {
    const val EXTRA_MODEL_ID = "modelId"
    const val EXTRA_MODEL_ASSET_PATH = "modelAssetPath"
    const val EXTRA_MODEL_FILE_PATH = "modelFilePath"
    const val EXTRA_MODEL_URL = "modelUrl"
    const val EXTRA_MODE = "mode"
    const val EXTRA_AUGMENTED_IMAGE_ASSET_PATH = "augmentedImageAssetPath"
    const val EXTRA_AUGMENTED_IMAGE_NAME = "augmentedImageName"
    const val EXTRA_AUGMENTED_IMAGE_WIDTH_METERS = "augmentedImageWidthMeters"
    const val EXTRA_AUGMENTED_IMAGE_ASSET_PATHS = "augmentedImageAssetPaths"
    const val EXTRA_AUGMENTED_IMAGE_NAMES = "augmentedImageNames"
    const val EXTRA_AUGMENTED_IMAGE_WIDTHS_METERS = "augmentedImageWidthsMeters"
    const val EXTRA_MARKER_DARA_POSITIONS = "markerDaraPositions"
    const val EXTRA_MARKER_DARA_ROTATIONS = "markerDaraRotations"
    const val EXTRA_MARKER_DARA_POSE_KNOWN = "markerDaraPoseKnown"
    const val EXTRA_MODEL_OFFSET_X_METERS = "modelOffsetXMeters"
    const val EXTRA_MODEL_OFFSET_Y_METERS = "modelOffsetYMeters"
    const val EXTRA_MODEL_OFFSET_Z_METERS = "modelOffsetZMeters"
    const val EXTRA_MODEL_SCALE_TO_UNITS = "modelScaleToUnits"
    const val EXTRA_MARKER_DARA_POSITION_X_METERS = "markerDaraPositionXMeters"
    const val EXTRA_MARKER_DARA_POSITION_Y_METERS = "markerDaraPositionYMeters"
    const val EXTRA_MARKER_DARA_POSITION_Z_METERS = "markerDaraPositionZMeters"
    const val EXTRA_MARKER_DARA_ROTATION_QX = "markerDaraRotationQx"
    const val EXTRA_MARKER_DARA_ROTATION_QY = "markerDaraRotationQy"
    const val EXTRA_MARKER_DARA_ROTATION_QZ = "markerDaraRotationQz"
    const val EXTRA_MARKER_DARA_ROTATION_QW = "markerDaraRotationQw"

    const val RESULT_EVENT = "event"
    const val RESULT_OBJECT_ID = "objectId"

    const val EVENT_OBJECT_CLICKED = "objectClicked"
    const val EVENT_CANCELLED = "cancelled"
}
